### PR TITLE
(fix) O3-3891: Adjust Change Language Modal Size to Small

### PR DESCRIPTION
**Pull request by Samstar10**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
This PR adjusts the size of the change-language pop-up modal to small.

## Screenshots
Find attached the screenshot with the changes.
Screenshot 2024-09-02 at 11 26 40

## Related Issue
https://openmrs.atlassian.net/browse/O3-3891

## Other
@denniskigen @vasharma05 please review.

### CODE REVIEW

**Comment by denniskigen** [comment]
Thanks for taking a stab at this, @Samstar10. As mentioned last week, we've created an [abstraction](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-styleguide/src/modals/index.tsx#L41) that handles creating the modal container element and injecting it it into the DOM. The idea behind this is that modals should be framework agnostic (the Angular form engine in O3 runs Angular and can leverage the same modal container we use in the React context). In https://github.com/openmrs/openmrs-esm-core/pull/1151, I tweaked the underlying implementation of the abstraction to support passing in a optional size prop to your `showModal` definition. Check out the PR description for a guide on how you could leverage that here to achieve the same goal.

**Comment by Samstar10** [comment]
> Thanks for taking a stab at this, @Samstar10. As I mentioned last week, we've built an [abstraction](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-styleguide/src/modals/index.tsx#L41) in the styleguide that handles creating the modal container and injecting it into the DOM. The goal is to make modals framework-agnostic, so both Angular (used in O3) and React can share the same modal container.
> 
> In [PR #1151](https://github.com/openmrs/openmrs-esm-core/pull/1151), I updated the abstraction to support an optional `size` prop in the `showModal` definition. You can check out the PR description for guidance on how to use it to achieve the same result.

Thank you @denniskigen. I will check it out and thank you for the feedback.

**Comment by vasharma05** [comment]
@Samstar10, you can refer #1155 from @suubi-joshua, and do the same for this PR too.
Thanks!

**Comment by Samstar10** [comment]
> @Samstar10, you can refer #1155 from @suubi-joshua, and do the same for this PR too. Thanks!

Thank you for the feedback @vasharma05. Let me get on it.

**Pull request closed without merging**
