### PR TITLE
Revert "O3-909"

### PR DESCRIPTION
**Pull request by brandones**
Reverts openmrs/openmrs-esm-core#219

This breaks `npx openmrs@next build`, which fails with

```
/home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs/node_modules/webpack/lib/buildChunkGraph.js:220
                const module = /** @type {Module} */ (block.getRootBlock());
                                                            ^

TypeError: block.getRootBlock is not a function
    at getBlockModules (/home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs/node_modules/webpack/lib/buildChunkGraph.js:220:47)
    at processBlock (/home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs/node_modules/webpack/lib/buildChunkGraph.js:563:24)
    at processQueue (/home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs/node_modules/webpack/lib/buildChunkGraph.js:740:6)
    at visitModules (/home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs/node_modules/webpack/lib/buildChunkGraph.js:1202:3)
    at buildChunkGraph (/home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs/node_modules/webpack/lib/buildChunkGraph.js:1367:2)
    at Compilation.seal (/home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs/node_modules/webpack/lib/Compilation.js:2937:3)
    at /home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs/node_modules/webpack/lib/Compiler.js:1120:20
    at /home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs/node_modules/webpack/lib/Compilation.js:2752:4
    at _next1 (eval at create (/home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at eval (eval at create (/home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
```

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Sorry there is no reason to revert it.

The build is only breaking when people have apparently two conflicting versions of webpack. My recommendation is to really remove the root cause, which is not that change.

To have two different versions of webpack means that something in the local project / repository is awfully wrong. I'd rather spend the time fighting the root cause, not going wild on reverts.

**Comment by brandones** [comment]
For anyone else experiencing this issue, the solution is to delete the `openmrs` directory in the `node_modules` being used. In the case of the error above:

```
rm -r /home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs
```

**Comment by FlorianRappl** [comment]
> rm -r /home/brandon/.npm/_npx/9145365975c7e340/node_modules/openmrs

Can you state *why* you are using a global version of that tool? It should be local only. That's the reason the tooling is part of the `devDependencies`.

**Comment by brandones** [comment]
It doesn't really make sense to build a distro in the context of a specific microfrontend. How are you imagining that people are actually using `openmrs build`?

For the usage of `openmrs build` that happens via the OpenMRS SDK, I've opened an issue about this. That tool does create a project-local `node_modules`; it should use that for `npx`. https://github.com/eirslett/frontend-maven-plugin/issues/1011

**Pull request closed without merging**
