### PR TITLE
O3-1205: Changed the position of the App menu and Hide toobar ToolTip

### PR DESCRIPTION
**Pull request by abertnamanya**
**Issue**: https://issues.openmrs.org/browse/O3-1205

**Changes**:
1. Changed the position of the toolTip of the App menu in the primary navigation 

app menu

2. Also changed the Hide toolbar tool tip position in the implementer tools dialog 

hidetoolbar

### CODE REVIEW

**Comment by ZacButko** [comment]
Hi @abertnamanya , Can you please update Pull Request to include a screenshot of the change working?

**Comment by denniskigen** [comment]
Additionally, please stick to using the provided pull request template; it provides for all the pre-requisites needed when contributing to this repository.

**Comment by denniskigen** [comment]
> Hi @abertnamanya , Can you please update Pull Request to include a screenshot of the change working?

Additionally, please stick to using the provided pull request template; it provides for all the pre-requisites needed when contributing to this repository.

**Comment by abertnamanya** [comment]
> Hi @abertnamanya , Can you please update Pull Request to include a screenshot of the change working?

Hi @ZacButko please review the attached screenshots

**Review by brandones — APPROVED** [review]

**Pull request merged**
