### PR TITLE
(fix) Login page tweaks

### PR DESCRIPTION
**Pull request by denniskigen**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This PR updates the Login component with the following changes:

- Removes the `value` Prop from the [PasswordInput](https://react.carbondesignsystem.com/?path=/docs/components-passwordinput--overview) component. This prevents passwords from appearing in the browser elements panel as they are typed in. This change has no impact on the login functionality. 
- Updates some CSS class names to follow the camel-case naming convention.
- Tweaks the login flow error logic so the user only gets navigated back to the `/login` route when logging in fails and the `showPasswordOnSeparateScreen` configuration property is set to `true`. When the `showPasswordOnSeparate` screen is set to `false`, the username and password are shown on the same screen and the same route (`/login`). It doesn't make sense to navigate the user to the route they're already on. Additionally, I've removed the code that clears the username and password inputs when login fails. 

- Adds translations for the logo title and alt text.

### Password revealed in the browser elements panel

https://github.com/openmrs/openmrs-esm-core/assets/8509731/b42bfa85-4596-4bac-b9b7-a102d5839bef

### CODE REVIEW

**Review by ibacher — APPROVED** [review]

**Comment by brandones** [comment]
@denniskigen This seems to have made it so that now filling a stored password from the browser doesn't work from the username entry page.

https://github.com/openmrs/openmrs-esm-core/assets/1031876/9949d593-4425-4846-99ea-586e59b40d0e

I think to fix this we probably want to refactor the login flow so that it all actually takes place in one component, nothing gets mounted or unmounted in the transition between the username "page" and the password "page".

**Comment by ibacher** [comment]
I think it's just [this line](https://github.com/openmrs/openmrs-esm-core/pull/1036/files#diff-a91a2347b0df20dbcee119ced765bfb975088ee720a045c3bc842080987c71a8L228) that needs to be reverted...

**Comment by brandones** [comment]
Well but that's the line that fixes the security issue that @denniskigen identified, where the password shows up in cleartext in the HTML. Though I'm not sure to what extent that constitutes a real problem, since
- It's unlikely that the value will get written to disk since it's not actually in HTML being sent over the wire
- At least in Chrome you don't need to authenticate to view stored passwords. Though I think for Apple products you do. So it would constitute a leak for Apple users, since it provides a way for an unauthenticated user with device access to obtain the stored cleartext password.

**Comment by ibacher** [comment]
I see... I can see how when screen-sharing / recording, it might become something of an issue, since you might end up accidentally recording a password you didn't mean to.

**Comment by denniskigen** [comment]
That's not ideal! Thanks for catching it, @brandones. I think it makes sense to fix that first and then worry about the security issue afterwards. Let me file a PR.

**Pull request merged**
