### PR TITLE
(chore) Release `v5.1.0`

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements
- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This PR cuts a new minor release of Core, `v5.1.0`. 

Core `5.1.0` contains various critical bug fixes for issues stemming from the `5.0.0` BREAKING release. In addition, it includes several new features and improvements.

#### Support for feature flags

This release introduces a new feature flagging system. This allows us to toggle features in the application on or off without having to release a new version of the application. This is useful for features that are still in development or features that are not yet ready for production use. Implementers will be able to toggle features on and off from the Feature Flags tab in the O3 Implementer Tools. 

See @brandones' quick demo of feature flags below:

Peek 2023-07-13 14-04

### Support for retrospective data entry

This release supports `visit-utils` and the `useVisit` hook to allow the user to manually set the "current visit" manually. Until now the "current visit" is just the latest visit with no end date. This change sets the stage for proper retrospective entry.

### More `v5.0.0`-related fixes

This release provides several fixes for issues that were introduced in the `5.0.0` release, including fixes to the configuration, extension, and translation systems. With these, we should be able to move forward with the `5.x` series of releases with more confidence.

### CODE REVIEW

**Review by vasharma05 — APPROVED** [review]

**Comment by brandones** [comment]
Hey if it's no trouble can we wait till https://github.com/openmrs/openmrs-esm-core/pull/733 is in? That's what I'd use to put patient flags and RDE behind feature flags. @denniskigen

**Comment by denniskigen** [comment]
> Hey if it's no trouble can we wait till #733 is in? That's what I'd use to put patient flags and RDE behind feature flags. @denniskigen

That's the plan, @brandones.

**Comment by ibacher** [comment]
@denniskigen Are you available to update this PR to deal with the addition of esm-feature-flags as a dependency of esm-extension?

**Comment by brandones** [comment]
Ok that one's in!

**Comment by brandones** [comment]
Your description is great, but I would drop the sentence "This allows us to toggle features in the application on or off without having to release a new version of the application." I don't think that's right. It's more that it allows us to release even if there's half-complete stuff in `main`. Which I think is the intention that comes through in the rest of your description.

**Comment by denniskigen** [comment]
Amended. Thanks, @brandones

**Pull request merged**
