### PR TITLE
#3026 my implementation for Animated Loading Visualization- GSOC 2024

### PR DESCRIPTION
**Pull request by mewanDimalsha**
# Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This project seeks to improve user experience on OpenMRS by introducing a visually engaging loading animation inspired by the OpenMRS logo. By tackling the issue of unpredictable loading times with an aesthetically pleasing solution, the aim is to boost user satisfaction and make the platform more user-friendly.

## Screenshots
image

https://github.com/openmrs/openmrs-esm-core/assets/115539818/97211760-2c13-4d62-808d-11655320d4df

### CODE REVIEW

**Comment by brandones** [comment]
Hi @mewanDimalsha . Who suggested this project? It says GSOC 2024 but I am not aware of any GSOC project this is relevant to.

Also, please respect the PR title norms, and include ticket links in the PR as required by the template.

**Comment by mewanDimalsha** [comment]
> Hi @mewanDimalsha . Who suggested this project? It says GSOC 2024 but I am not aware of any GSOC project this is relevant to.
> 
> Also, please respect the PR title norms, and include ticket links in the PR as required by the template.

image
This is the project and I have submitted the project proposal but I was not selected yet. This is the thing I have done for this project proposal. 
[https://openmrs.atlassian.net/browse/O3-3026](https://openmrs.atlassian.net/browse/O3-3026)

**Comment by mewanDimalsha** [comment]
Dear sir,

I sent the comment for this in the relevant PR

**Comment by brandones** [comment]
A 90 hour project for that??? :laughing: That's awesome. We should get a full anime series intro sequence, complete with power metal theme song, for that kind of time.

Joking aside, thank you for this contribution, and clarifying what it's for. I'll leave it to @jayasanka-sack from here, but I suspect that this feature needs design.

**Comment by brandones** [comment]
Patients come in one by one :guitar::notes: 
The doctors' work has just begun
Fighting to support UHC
Health systems for you and me
Filing orders, labs and tests 
OooopenM-R-S :guitar::zap:

**Comment by ibacher** [comment]
TBH, if we integrate it with a check for "is the backend starting up", I think it'd be useful and still very straight-forward.

**Pull request closed without merging**
