### PR TITLE
(chore) Upgrade to Yarn V4

### PR DESCRIPTION
**Pull request by ibacher**
## Requirements
- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and **design documentation**.

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

Just bumps us to Yarn v4. Plugins should be included already.

### CODE REVIEW

**Comment by jayasanka-sack** [comment]
@ibacher after this change, the ["Run ESM Core E2E Tests" job](https://ci.openmrs.org/browse/REFAPP-D3X-RECET-1914/log) fails to run yarn install as the agent has Node v16. Could you please let me know how we can upgrade the yarn version of agents?

**Comment by ibacher** [comment]
@jayasanka-sack We use NVM on Bamboo; I already changed the job to reflect that. That said, I don't really understand the purpose of running these tests at this point? Evidentially, we're not sending notifications on failure or anything and the tests are basically going to be identical to the test we run before _and_ after merging the PR on GitHub...

**Comment by jayasanka-sack** [comment]
Hi Ian, it seems it can't find `nvm` where it log `sh: 11: nvm: not found`. 
https://ci.openmrs.org/browse/REFAPP-D3E-354/log

By the way, I've configured it to send an email to the infra mail. In order to send a message to slack, I need privilege on bamboo to create a webhook.

**Comment by jayasanka-sack** [comment]
Update: No need to work with a webhook, slack messages can be posted via email.

**Comment by ibacher** [comment]
@jayasanka-sack Please use a webhook for this.

**Comment by ibacher** [comment]
At least for Slack integration. Emails are not free.

**Pull request merged**
