### PR TITLE
(fix) O3-3595: Use correct per-locale calendar in OpenmrsDatepicker

### PR DESCRIPTION
**Pull request by kajambiya**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
There was an issue with the datepicker when the selected locale was amharic; It wasn't correctly resolving the maxValue and whenever a value was selected, it would resolve to a gregorian date value.

## Screenshots

https://github.com/user-attachments/assets/d1f62d29-dbd0-46be-8ba5-d8fba1ec28d2

### CODE REVIEW

**Comment by gracepotma** [comment]
@denniskigen or @ibacher can you prioritize reviewing this 3-line PR? Will be very helpful for the Ethiopia team.

**Comment by denniskigen** [comment]
I've tested this out locally and it appears to work as expected. Thanks, @kajambiya.

**Review by denniskigen — APPROVED** [review]
LGTM

**Review by NethmiRodrigo — APPROVED** [review]

**Comment by NethmiRodrigo** [comment]
LGTM! Thanks @kajambiya

**Pull request merged**
