### PR TITLE
Lint for disallowed imports

### PR DESCRIPTION
**Pull request by brandones**
Produces errors like

Screenshot from 2021-08-25 08-47-18

### CODE REVIEW

**Review by FlorianRappl — APPROVED** [review]
This is great - should we also include things like carbon icons, `lodash-es` (only submodules should be considered), etc.?

**Comment by brandones** [comment]
Yeah, those are good ones, thanks

**Comment by brandones** [comment]
Oops, looks like we'll need https://github.com/typescript-eslint/typescript-eslint/issues/2661 fixed. Amazingly, a PR was submitted 4 days ago: https://github.com/typescript-eslint/typescript-eslint/pull/3775 . Fingers crossed it goes in soon. This PR should be considered blocked on it. I'll close this PR if that PR closes or stalls out.

**Comment by brandones** [comment]
Since `carbon-react-components` now tree-shakes well, we no longer need https://github.com/typescript-eslint/typescript-eslint/issues/2661 fixed. The rule has been updated to forbid imports from `carbon-components-react/lib`, which does not tree-shake well.

**Pull request merged**
