### PR TITLE
(chore) Add chinese language files 

### PR DESCRIPTION
**Pull request by jona42-ui**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

### CODE REVIEW

**Comment by jona42-ui** [comment]
cc @ibacher @rbuisson

**Comment by ibacher** [comment]
@jona42-ui It's also necessary to modify the file [here](https://github.com/openmrs/openmrs-esm-core/blob/d0a86cec115e2f22f520bc972c608af041a14df4/tools/i18next-parser.config.js#L45) to include the new locales.

**Comment by jona42-ui** [comment]
updated thanks @ibacher

**Review by denniskigen — APPROVED** [review]
Thanks, @jona42-ui. This LGTM. Do we also need `zh_CN` translations, @ibacher, https://github.com/befantasy?

**Comment by ibacher** [comment]
@denniskigen We can always add them later.

**Pull request merged**
