### PR TITLE
(chore) O3-2935: Trigger E2E tests when there is  a change in package.json

### PR DESCRIPTION
**Pull request by kdaud**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [x] My work includes tests or is validated by existing tests.
- [x] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
Refer to this convo: https://openmrs.slack.com/archives/CHP5QAE5R/p1709730208547039

## Related Issue

https://issues.openmrs.org/browse/O3-2935

### CODE REVIEW

**Comment by kdaud** [comment]
@denniskigen @jayasanka-sack @ibacher could you review this PR? Thanks!

**Review by jayasanka-sack — APPROVED** [review]
Thanks, @kdaud !

**Comment by jayasanka-sack** [comment]
@kdaud Can you update other repos too?

**Comment by kdaud** [comment]
@jayasanka-sack I've not seen the rule applied elsewhere except on core. Are you suggesting to apply the rule on other esm repos having E2E tests?

**Comment by jayasanka-sack** [comment]
I see. We might not need to have it on other repos, as they don't come with toolings like the core.

**Pull request merged**
