### PR TITLE
KH-239: Translate login page to km

### PR DESCRIPTION
**Pull request by kdaud**
## Requirements
- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.

#### For changes to apps
- [x]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [x] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Related Issue

https://mekomsolutions.atlassian.net/browse/KH-239

### CODE REVIEW

**Review by vasharma05 — COMMENTED** [review]
Are these all the required translations?
Please compare it with en.json

**Comment by kdaud** [comment]
@vasharma05 I've crosschecked and found a few other translation applicable to km login page. I will have to update this PR once I get them!

**Comment by rbuisson** [comment]
@kdaud , could you maybe set the PR as draft until it's complete?

**Review by vasharma05 — APPROVED** [review]
LGTM!
Thanks

**Pull request merged**
