### PR TITLE
revert O3-3866

### PR DESCRIPTION
**Pull request by mogoodrich**
# Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

### CODE REVIEW

**Comment by mogoodrich** [comment]
This is just a revert, and all tests have passed, going to merge without review.

**Comment by vasharma05** [comment]
Hi @mogoodrich!
This PR doesn't break the build here, but in the patient chart/ management, the Typescript is failing for all workspace-related tests.
Can you please look into it?
Thanks!

**Comment by mogoodrich** [comment]
Thanks @vasharma05 .  How do I reproduce?  I just ran yarn verify against patient-chart and patient-management without issue. (and the builds for patient-chart and patient-management in github are passing)  Note that there is a corresponding revert I made in patient-chart that needs to be pulled in as well.

**Comment by vasharma05** [comment]
Hi @mogoodrich, to reproduce the issue, we need to bump `@openmrs/esm-framework` version and then run `yarn verify`. You can see the failing tests [here](https://github.com/openmrs/openmrs-esm-patient-chart/actions/runs/10941342554/job/30375766268?pr=2022)

**Pull request merged**
