### PR TITLE
(feat) allow useLocations react hook to take in tag parameter

### PR DESCRIPTION
**Pull request by chibongho**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

We currently have a `useLocations()` hook which calls the v1 REST API for a list of locations. The REST API can already take in an additional parameter to specify a tag to filter by all locations with that tag. This PR changes the hook to support passing a tag parameter.

## Other
Note that the git commit hook generated some styling and documentation changes that I had to manually re-add into the commit.

### CODE REVIEW

**Review by mogoodrich — COMMENTED** [review]
Thanks @chibongho ! Genrerally LGTM,  what's up with those SnackarDescriptor name changes?

**Review by mseaton — COMMENTED** [review]
LGTM, same comment as @mogoodrich about the Snackbar file changes that appear

**Comment by chibongho** [comment]
The git commit hook changed the casing of those file names.

**Comment by denniskigen** [comment]
These are fine. The pre-commit hook runs a [task](https://github.com/openmrs/openmrs-esm-core/blob/9db3402971708c5022be022facb2a0ebfd653a90/.husky/pre-commit#L8) that updates the markdown files that updates our API docs. They likely got updated in a previous commit that @chibongho might not have had on his local.

**Review by denniskigen — APPROVED** [review]
LGTM, @chibongho.

**Pull request merged**
