### PR TITLE
 (fix) reduced spacing between skeletons in the location-picker

### PR DESCRIPTION
**Pull request by Denywiryk**
## Requirements
- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.

#### For changes to apps
- [x]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

The spacing between the skeletons was more than expected but then i have made an alignment and reduced to meet  the jiira issue  [issue-number](https://issues.openmrs.org/browse/O3-2069)
## Related Issue

spacing between skeletons more than expected
opemrsskeleton

spacing reduced  to below
openmrs2

### CODE REVIEW

**Review by njiddasalifu — CHANGES_REQUESTED** [review]
looks good, you can try to squash your commits to one and also add more description to the PR including the ticket

**Comment by ibacher** [comment]
> you can try to squash your commits

We actually ask that developers _not_ squash their commits. It makes it harder to follow-up on PR reviews. We can handle squashing when it's mergeable.

**Comment by ibacher** [comment]
> jiira issue [issue-number](https://issues.openmrs.org/browse/O3-2069)

Please write links like `[O3-2069](https://issues.openmrs.org/browse/O3-2069)`

**Comment by Denywiryk** [comment]
I had created a new branch without switching to master branch and  at the same time experiencing merging conflicts

**Pull request closed without merging**
