### PR TITLE
BREAKING O3-806: Migrate from openmrs-spa.org -> dev3.openmrs.org

### PR DESCRIPTION
**Pull request by ibacher**
## Summary

dev3.openmrs.org has now been configured to serve contents from Digital Ocean, like openmrs-spa.org does, so it now feels like the right time to migrate to the new development version.

## Related Issue

https://issues.openmrs.org/browse/O3-806

## Other

_None._

### CODE REVIEW

**Comment by ibacher** [comment]
@gracepotma FYI

**Review by jonathandick — COMMENTED** [review]
Do we need to also update the ci-process for other repos? Also, for clarity, we will continue to use DO as a CDN for now, right?

**Review by brandones — APPROVED** [review]

**Comment by ibacher** [comment]
@jonathandick 
> Also, for clarity, we will continue to use DO as a CDN for now, right?

Yes

> Do we need to also update the ci-process for other repos?

Not to use dev3 as the dev / CI environment since we're still serving the files from DO.

**Comment by gracepotma** [comment]
60fps_parrot
60fps_parrot
60fps_parrot

**Comment by ibacher** [comment]
I forgot this wasn't merged yet. I'm going to merge it on Monday so things stay working over the weekend.

**Comment by sherrif10** [comment]
This looks good to me cc @ibacher  :small_airplane:

**Pull request merged**
