### PR TITLE
(chore) Only trigger e2e tests when relevant code has changed

### PR DESCRIPTION
**Pull request by ibacher**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This adds a step to the e2e test workflow that will skip running the actual tests unless some relevant file has been modified (basically, relevant files are any source code that is not simply in a Jest test). I think I've got everything and got the picomatch syntax right, but we should verify that. Note that since this PR updates the e2e workflow file itself, it _should_ trigger a full e2e test run.

### CODE REVIEW

**Comment by ibacher** [comment]
Well, this has pretty conclusively proven that this can stop the e2e tests from being triggered. Let's see if it can trigger them...

**Comment by denniskigen** [comment]
Did you get it working reliably, @ibacher?

**Comment by ibacher** [comment]
Yes. With the first couple of commits the e2e tests didn't run at all (hence taking seconds), but now the e2e tests were successfully triggered because the PR updates the workflow file.

**Review by denniskigen — APPROVED** [review]
LGTM! Thanks, @ibacher.

**Comment by kdaud** [comment]
> Well, this has pretty conclusively proven that this can stop the e2e tests from being triggered. Let's see if it can trigger them...

Positive feedback → Yes, the logic works pretty well. Thanks, @ibacher !

@ibacher @denniskigen @jayasanka-sack additionally I suggest that when there is a change in the library package (ie upgrade/downgrade) the e2e tests should be as well triggered. Why? Ideally a change in a library version may introduce a breaking change in the E2E tests so having them triggered can help to flag out the issue at an earlier stage.

So if the idea is embraced, then we can push [this](https://github.com/openmrs/openmrs-esm-core/pull/951) change into main. Happy merging....

**Pull request merged**
