### PR TITLE
O3-651: Removed height declaration so that error messages are displayed on th…

### PR DESCRIPTION
**Pull request by nravilla**
…e login card

## Requirements

- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Screenshots

_None._

## Related Issue

_None._

## Other

_None._

### CODE REVIEW

**Comment by nravilla** [comment]
This commit is for https://issues.openmrs.org/browse/O3-651

**Comment by brandones** [comment]
Hi @nravilla , nice work on this. Could you please post screenshots, since this impacts the UI?

**Comment by brandones** [comment]
Ping @nravilla

**Comment by denniskigen** [comment]
Hey, @nravilla. Correct me if I'm wrong but hasn't this been obviated by https://github.com/openmrs/openmrs-esm-core/pull/292?

**Comment by brandones** [comment]
Yeah, but I still suspect we're better off without the `height` attribute @denniskigen . Better to let the browser figure it out based on the contents.

**Review by brandones — APPROVED** [review]

**Pull request merged**
