### PR TITLE
(chore) Release v6.0.0

### PR DESCRIPTION
**Pull request by denniskigen**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

Cuts a new major release of Core, `v6.0.0`, with breaking changes, new features, and bug fixes. Here's the draft changelog:

### Breaking changes

* (BREAKING) Retire concept of ConnectedExtension by @ibacher in https://github.com/openmrs/openmrs-esm-core/pull/1154

### Features

* (feat) O3-4249: Add component to support rendering an icon if it exists by @ibacher in https://github.com/openmrs/openmrs-esm-core/pull/1220
* (feat) Add pharmacy pictogram by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1218
* (feat) O3-4216: Add `Programs` icon to CarbonMRS icon pack by @Munyua123 in https://github.com/openmrs/openmrs-esm-core/pull/1212
* (feat) O3-4215: Enable Environment Specification for Shell Builds by @jayasanka-sack in https://github.com/openmrs/openmrs-esm-core/pull/1211
* (feat) Use gender icons from icon framework in patient header by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1208
* (feat) O3-4168: Add gender icons to the CarbonMRS icon pack by @mccarthyaaron in https://github.com/openmrs/openmrs-esm-core/pull/1207
* (feat) Add `in-patient` pictogram by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1205
* (feat) Add translation for "Save" to core translations library by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1204
* (feat) O3-4196: Improve optional backend dependencies functionality by @mogoodrich in https://github.com/openmrs/openmrs-esm-core/pull/1203
* (feat) O3-4170: Add `Syringe` icon to CarbonMRS icon pack by @Munyua123 in https://github.com/openmrs/openmrs-esm-core/pull/1196
* (feat) O3-4160: Patient header redesign by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1195
* (feat) O3-4161: Add `Report` icon to CarbonMRS icon pack by @Munyua123 in https://github.com/openmrs/openmrs-esm-core/pull/1194
* (feat) O3-4143: `useLocations` should support searching by tag or query string by @mogoodrich in https://github.com/openmrs/openmrs-esm-core/pull/1191
* (feat) Allow passing action menu state to the workspace container by @vasharma05 in https://github.com/openmrs/openmrs-esm-core/pull/1189
* (feat) Add translation override for district address field by @makombe in https://github.com/openmrs/openmrs-esm-core/pull/1188
* (feat) O3-4074: Add `CheckmarkOutlineIcon` to the styleguide by @usamaidrsk in https://github.com/openmrs/openmrs-esm-core/pull/1176
* (feat) Add variable name extractor to expression runner by @ibacher in https://github.com/openmrs/openmrs-esm-core/pull/1173
* (feat) O3-3774: Add Nav Group implementation to the styleguide by @hadijahkyampeire in https://github.com/openmrs/openmrs-esm-core/pull/1116
* (feat) O3-4018: Add `Information` and `CheckmarkFilled` icons to the styleguide by @usamaidrsk in https://github.com/openmrs/openmrs-esm-core/pull/1163
* (feat) Disable most automatic revalidations by default by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1157
* (feat) O3-3759: Refactor `usePatient` hook to leverage `useSWR` by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1156
* (feat) O3-3889: Update `Change Password` modal to the `sm` variant by @suubi-joshua in https://github.com/openmrs/openmrs-esm-core/pull/1155
* (feat) Make it possible to change modal container size by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1151
* (feat) Add patient registration pictogram by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1150
* (feat) O3-3859: Ability to customize or add logos to login page footer by @suubi-joshua in https://github.com/openmrs/openmrs-esm-core/pull/1127
 
### Refactors

* (refactor) Refactor reusable patient banner components by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1209
* (refactor) Switch visit requests to use promises instead of observables by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1184
* (refactor) Refactor REST API calls to reuse `restBaseUrl` by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1168

### Bug fixes

* (fix) O3-4327: Fix `openmrsFetchAll` calling url twice when more than 1 page is fetched by @kb019 in https://github.com/openmrs/openmrs-esm-core/pull/1217
* (fix) Fix typo in OpenMRS component decorator for strict mode by @kb019 in https://github.com/openmrs/openmrs-esm-core/pull/1213
* (fix) Fix change password modal by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1210
* (fix) Fixed wrong print icon name by @CynthiaKamau in https://github.com/openmrs/openmrs-esm-core/pull/1201
* (fix) O3-4135: Disable help icon while user is logged out by @suubi-joshua in https://github.com/openmrs/openmrs-esm-core/pull/1186
* (fix) O3-4134: Translation overrides not being overridden correctly by @ibacher in https://github.com/openmrs/openmrs-esm-core/pull/1187
* (fix) O3-3627: Preserve original filename when saving an attachment by @suubi-joshua in https://github.com/openmrs/openmrs-esm-core/pull/1183
* (fix) O3-3888: Tweak help menu hover state  by @elishabantana in https://github.com/openmrs/openmrs-esm-core/pull/1179
* (fix) Fix docstring for `extractVariableNames` by @brandones in https://github.com/openmrs/openmrs-esm-core/pull/1178
* (fix) Expression evaluator should use typeof not instanceof to detect functions by @samuelmale in https://github.com/openmrs/openmrs-esm-core/pull/1174
* (fix) O3-4018: Fix `checkmark--filled.svg` for CheckmarkFilledIcon by @usamaidrsk in https://github.com/openmrs/openmrs-esm-core/pull/1172
* (fix) O3-4018: Cleanup `checkmark--filled.svg` for CheckmarkFilledIcon by @usamaidrsk in https://github.com/openmrs/openmrs-esm-core/pull/1171
* (fix) O3-4018: Fix `CheckmarkFilled` icon registration by @usamaidrsk in https://github.com/openmrs/openmrs-esm-core/pull/1170
* (fix) Pass patient object to the banner action buttons by @vasharma05 in https://github.com/openmrs/openmrs-esm-core/pull/1158
* (fix) O3-3891: Adjust the `Change Language` modal to size `sm` by @Samstar10 in https://github.com/openmrs/openmrs-esm-core/pull/1162
* (fix) O3-3709: Fix `useOpenmrsFetchAll` not fetching more than 2 pages by @chibongho in https://github.com/openmrs/openmrs-esm-core/pull/1160
* (fix) Wrap Workspace in suspense container by @ibacher in https://github.com/openmrs/openmrs-esm-core/pull/1148
* (fix) O3-3189: Fix `useOpemrsInfinite` hook to correctly take in URL by @chibongho in https://github.com/openmrs/openmrs-esm-core/pull/1146

### Housekeeping

_Transifex automated updates omitted for brevity_

* (chore) Add missing translations for header menu tooltips by @usamaidrsk in https://github.com/openmrs/openmrs-esm-core/pull/1219
* (chore) Flag duplicate imports by @denniskigen in https://github.com/openmrs/openmrs-esm-core/pull/1206
* (chore) Bump Playwright by @kdaud in https://github.com/openmrs/openmrs-esm-core/pull/1199
* (chore) O3-4011: Make patient banner patient identifiers a reusable component by @chibongho in https://github.com/openmrs/openmrs-esm-core/pull/1159
* (chore) O3-4018: Add checkmarkFilled and information icons mocks by @usamaidrsk in https://github.com/openmrs/openmrs-esm-core/pull/1166
* (chore) O3-3973: Cache playwright browsers install step in E2E workflow by @virajwathsalag in https://github.com/openmrs/openmrs-esm-core/pull/1147

### Miscellaneous

* (test) O3-4011 - Add stub for `PatientBannerPatientIdentifier` to styleguide mock by @chibongho in https://github.com/openmrs/openmrs-esm-core/pull/1181

### CODE REVIEW

**Review by ibacher — APPROVED** [review]

**Comment by samuelmale** [comment]
Can we hold off merging this yet? I'm working on a minor commit around the expression runner.

**Comment by vasharma05** [comment]
Hi @denniskigen @ibacher!
I have my PR #1185 up for review for a few days now, which should go in this release. Can you please review the PR, before merging this PR?
Thanks!

**Comment by vasharma05** [comment]
Hi @denniskigen @ibacher!
Also, we need to find a solution for https://openmrs.atlassian.net/issues/O3-4254 as we are not seeing the `obs-by-encounter` widget on the patient chart due to an error in the `useConfig`.
Thanks!

**Review by NethmiRodrigo — APPROVED** [review]

**Review by samuelmale — APPROVED** [review]

**Comment by vasharma05** [comment]
Hi @samuelmale, as shared above, there's a blocking issue which needs to be merged in before the release.

**Comment by samuelmale** [comment]
My bad @vasharma05, It was an oversight from my end! Could you address this issue in a patch release?

**Comment by vasharma05** [comment]
Hi @samuelmale!
Yes, I am looking into it, and am also awaiting review on #1185. 
Thanks!

**Pull request merged**
