### PR TITLE
Carbonize and style implementer-tools

### PR DESCRIPTION
**Pull request by brandones**
Screenshot from 2020-11-19 23-52-09

I am not a designer. Forgive me.

### CODE REVIEW

**Review by jonathandick — APPROVED** [review]
LGTM

**Comment by jonathandick** [comment]
Would love to see the modules listed as buttons in the left side (maybe https://www.carbondesignsystem.com/components/UI-shell-left-panel/usage), and then display the config itself in the "content area". ++ with a searchable filter so you can find the config you're looking for. (I realize there are a lot of ideas you/we probably have about how to display these things)

**Review by denniskigen — APPROVED** [review]
A tad too white but looks good to my programmer :eyes:

**Comment by brandones** [comment]
Thanks guys! And @jonathandick I really appreciate the ideas. Keep em coming. I'll look into that.

**Comment by jonathandick** [comment]
Also, it's not using the carbon font in the buttons or I think elsewhere.

**Comment by brandones** [comment]
And @denniskigen , I agree that I would prefer it with sort of a dark style. I just didn't want to be messing with CSS that much while doing this :stuck_out_tongue_closed_eyes:

**Comment by gracepotma** [comment]
Ship it - looking better every day. This is great to see @brandones and @denniskigen 🚀

**Pull request merged**
