### PR TITLE
(fix) Properly set app shell public path

### PR DESCRIPTION
**Pull request by ibacher**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This just sets the Webpack public path correctly in the app shell. This should ensure that fonts, etc. are always loaded correctly.

### CODE REVIEW

**Review by denniskigen — APPROVED** [review]
LGTM. Thanks, @ibacher.

**Comment by denniskigen** [comment]
@ibacher fonts are failing to load on dev3. Looks like `SPA_PATH` is not getting interpolated correctly:

CleanShot 2024-06-18 at 9  19 08@2x

**Comment by ibacher** [comment]
Yeah, I'm aware. This was on the docket to be reverted until I can figure that out.

**Comment by denniskigen** [comment]
Did the revert do the trick?

**Comment by ibacher** [comment]
Seems like a mixed bag...

**Comment by denniskigen** [comment]
Back working for me now

**Pull request merged**
