### PR TITLE
(fix) O3-2265: Change user menu label to "My Account"

### PR DESCRIPTION
**Pull request by usamaidrsk**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This PR changes the label on the User Nave Icon from User to My Account as suggested from the attached ticket

## Screenshots

image

## Related Issue

[O3-2265](https://openmrs.atlassian.net/browse/O3-2265)

### CODE REVIEW

**Comment by denniskigen** [comment]
You should update the Login and Logout specs to fix the E2E failures.

**Review by mseaton — APPROVED** [review]
LGTM, though are we supposed to manually change translation files like this?  I guess  we probably need to because we haven't changed the message key, just the value?

**Comment by ibacher** [comment]
> though are we supposed to manually change translation files like this?

No. Only the en.json file should be updated in the PR.

**Review by denniskigen — APPROVED** [review]
Happy with this, @ibacher?

**Pull request merged**
