### PR TITLE
(feat) Enable online and offline extensions through configuration

### PR DESCRIPTION
**Pull request by icrc-jofrancisco**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [x] My work includes tests or is validated by existing tests.
- [x] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

Implemented feature to enable both online and offline extensions based on configuration settings. The configuration options provide users with control over the extension. 

Below is an example of how to change/enable the display condition (online and offline) using configuration:

```{
  "@openmrs/esm-home-app": {
    "extensionSlots": {
      "homepage-widgets-slot": {
        "order": [
          "active-visits-widget"
        ],
        "configure": {
          "active-visits-widget": {
            "Display conditions": {
              "online": true,
              "offline": true,
              "privileges": [
                "Widget: active visits"
              ]
            }
          }
        }
      }
    }
  }
}
```

In this case, the widget would be shown in both online and offline mode.

## Other

Thanks, 
CC: @ibacher

### CODE REVIEW

**Comment by suubi-joshua** [comment]
@icrc-jofrancisco could you provide ticket number in the PR title.

**Comment by icrc-jofrancisco** [comment]
> @icrc-jofrancisco could you provide ticket number in the PR title.

Hi @suubi-joshua , 
There is no ticket associated with this pull request, it is just a requirement for our distribution.
Thanks,

**Comment by suubi-joshua** [comment]
> > @icrc-jofrancisco could you provide ticket number in the PR title.
> 
> Hi @suubi-joshua , There is no ticket associated with this pull request, it is just a requirement for our distribution. Thanks,

Ohhh my bad, great work done though.

**Review by vasharma05 — COMMENTED** [review]
Looks good to me, but will require @ibacher for final merge.
Thanks!

**Review by ibacher — APPROVED** [review]

**Pull request merged**
