### PR TITLE
4.0

### PR DESCRIPTION
**Pull request by brandones**
This is a working branch for the 4.0 release. We will merge breaking changes to this branch until we are ready to merge it to master. The target date to merge to master is May 24.

Goals:
- [x] [Upgrade to React 18](https://issues.openmrs.org/browse/O3-917)
- [x] [Upgrade to react-router 6](https://issues.openmrs.org/browse/O3-921)
- [x] [Upgrade to Carbon 11](https://issues.openmrs.org/browse/O3-1285)
- [x] Upgrade to Testing Library 13
- [x] Upgrade to Jest 28

### CODE REVIEW

**Review by ZacButko — APPROVED** [review]

**Comment by denniskigen** [comment]
Bumped to get the branch level with master.

**Comment by denniskigen** [comment]
Hey @brandones, could you please update v4.x.x of esm-core to include the latest features and fixes? This [PR](https://github.com/openmrs/openmrs-esm-core/pull/447) in particular is necessary for me to be able to wrap up work on the esm-patient-chart 4.0 branch.

**Comment by brandones** [comment]
@denniskigen Done, 4.0.0-pre.1 released.

**Comment by gracepotma** [comment]
Update as of July 21: Reason this has not been merged yet: branches keep changing, we're slowly trying to put this together but just haven't had enough combined time to move forward. See: https://openmrs.slack.com/archives/CHP5QAE5R/p1657758245483639 - @denniskigen wants to test the entire build locally next.

**Comment by denniskigen** [comment]
I'm unblocked @gracepotma! Thanks so much to the inimitable @brandones!

**Comment by brandones** [comment]
Oh no, I seem to have un-done a bunch of Dennis's work resolving merge errors. I'm going to see if I can `git reflog` my way out of this.

**Comment by denniskigen** [comment]
Hey @ibacher, this specific 4.0 branch is ready sans one fix - I can't get the Devtools overrides panel working and I'm not sure why yet.

**Comment by brandones** [comment]
I've just done a pretty ambitious rebase to clean up the history enough to be able to bisect the issue with devtools.

**Comment by brandones** [comment]
I finished rebasing and realized that, just as mysteriously as the issue with Devtools had appeared, it was gone. Devtools is working.

Would be great if someone could double check my work, and then let's ship.

@denniskigen or @ibacher , whoever has the most recent checkout from before my rebase, if you have time to do this and report back, that would be great:

```
# keeping your own local 4.0 branch as it is, without pulling
git fetch
git diff 4.0 origin/4.0 > brandons-changes.diff
```

I think I did a good job checking, but it would be helpful to double-check I didn't screw anything up.

**Comment by brandones** [comment]
@denniskigen reports that the one remaining issue is something with the "form engine wrapper," possibly having to do with the [extra webpack config](https://github.com/openmrs/openmrs-esm-patient-chart/blob/master/packages/esm-form-entry-app/extra-webpack.config.js).

**Pull request merged**
