### PR TITLE
Removed unnecessary data from ExternalRefLinks in primary navigation's configuration

### PR DESCRIPTION
**Pull request by vasharma05**
## Requirements
- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

#### For changes to apps
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/master/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
Removed unnecessary data from ExternalRefLinks in primary navigation's configuration.
I have removed 2 unnecessary keys from the ExternalRefLinks: 
1. Enabled -> Should we showcase external links in the app menu
2. Visible -> Should a link present in the configuration be visible in the app menu

I added these before to make them easier for the user to maintain the links, but find these redundant now.

## Screenshots

image
See the bottom right corner.

### CODE REVIEW

**Review by brandones — APPROVED** [review]
Seems reasonable to me! Thanks!

**Comment by brandones** [comment]
Please fix the build before merging

**Comment by vasharma05** [comment]
Thank you @brandones for the help, I missed the update, don't know how, since I keep everything updated, will be more careful the next time.

**Comment by brandones** [comment]
No worries Vinnet, nice work!

**Pull request merged**
