### PR TITLE
(feat) Add CarbonMRS SVGs

### PR DESCRIPTION
**Pull request by ibacher**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This adds all of the current SVGs available on Zero Height. This means that all placeholder SVGs are replaced with their CarbonMRS counterparts, except for Save and Reset.

## Other

Although CarbonMRS icons are similar to Carbon icons, they are all re-drawn with different size and line-weights, etc. from the Carbon set. This means they may looks slightly off next to Carbon icons. The solution here is to replace all the app icons with CarbonMRS equivalents.

Although this PR includes all the SVGs, I have not actually implemented every icon. This PR only adds 6 or so new icons. I've also included all of the pictograms, but none of the pictograms are actually used at this point.

### CODE REVIEW

**Review by denniskigen — APPROVED** [review]
LGTM! Thanks, @ibacher.

**Comment by denniskigen** [comment]
The only thing that looks off to me so far is the `X` button in the workspace: 

CleanShot 2024-05-31 at 11  20 31@2x

**Comment by ibacher** [comment]
@denniskigen I think I just fixed that? I was having some issues with the primary nav icons and I probably set the default too large.

**Comment by denniskigen** [comment]
Looks good! Thanks!

**Pull request merged**
