### PR TITLE
(feat) Add a no-op SW when running with offline disabled

### PR DESCRIPTION
**Pull request by ibacher**
## Requirements
- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and **design documentation**.

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

Does what it says in the commit message.

### CODE REVIEW

**Comment by ibacher** [comment]
@denniskigen When you get a chance (no rush), could you try this out? It seems to work for me, but I'm worried that my browser isn't as scarred by service workers as yours is.

**Comment by denniskigen** [comment]
Seems to work fine on Firefox, but not on Chrome. I'm getting some weird results on Chrome.

**Comment by ibacher** [comment]
Ok, the underlying issue here appears to be that Chrome is re-installing the service-worker.js file, but seems to be using a cached copy, which is fixable, but hard to undo for broken browsers.

**Comment by ibacher** [comment]
@denniskigen Ok... Looked at this again and it was embarrassingly, stupidly easy to fix. Basically, we're using the `InjectManifest` plugin from Workbox that allows a lot of control over how the manifest is processed. It does this by injecting the manifest (the fixed files that need to be cached) into the variable named `self.__WB_MANIFEST`, basically in the same manner as Webpack's Define Plugin does (i.e., replace a matching string with the contents. I had this:

```ts
self.__WB_MANIFEST = [];
```

Which resulted in something like:

```ts
[{/* some JS object */}, {/* some JS object */}, {/* some JS object */}, /* ... */] = [];
```

Which fails because JS reads that as a destructuring assignment. Since that lead to an exception being thrown when the SW was loaded, the new service worker was never actually installed.

I've fixed things so that an empty manifest is generated and assigned to a normal JS variable.

**Comment by denniskigen** [comment]
LGTM! Thanks, @ibacher!

**Review by denniskigen — APPROVED** [review]

**Pull request merged**
