### PR TITLE
(feat) O3-3889: Update Change Password modal to the `sm` variant

### PR DESCRIPTION
**Pull request by suubi-joshua**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
Update 'Change password' modal to use the small modal component. 

## Screenshots

CleanShot 2024-09-20 at 11  53 05@2x

## Related Issue

https://openmrs.atlassian.net/browse/O3-3889

### CODE REVIEW

**Review by vasharma05 — APPROVED** [review]
Thanks @suubi-joshua!

**Comment by vasharma05** [comment]
@suubi-joshua, please update the corresponding tests.
Thanks!

**Comment by denniskigen** [comment]
LGTM. Thanks, @suubi-joshua!

**Comment by suubi-joshua** [comment]
> LGTM. Thanks, @suubi-joshua!

Thank you

**Pull request merged**
