### PR TITLE
(refactor) Switch visit requests to use promises instead of observables

### PR DESCRIPTION
**Pull request by denniskigen**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

Ports over requests to the Visit API to use promise-based fetch requests instead of observables. Promises are generally simpler to work with than observables, and this should make the code easier to understand. This change also makes the code more consistent with other requests the frontend makes to the REST API.

I've also amended the `UpdateVisitPayload` type annotation to a partial of `NewVisitPayload`, as not all fields are required when updating a visit. We should only really need to provide the stop datetime when ending a visit, for example.

### CODE REVIEW

**Comment by denniskigen** [comment]
@ibacher Is this technically a breaking change?

**Comment by ibacher** [comment]
Technically, yes, but maybe we can ignore that?

**Review by ibacher — APPROVED** [review]

**Comment by denniskigen** [comment]
@ibacher I think I've covered all the bases with my linked PRs.

**Comment by ibacher** [comment]
Yeah, we'd exepct the tests to break until everything is updated

**Pull request merged**
