### PR TITLE
(feat) O3-3461: Create a common reusable function for printing

### PR DESCRIPTION
**Pull request by jnsereko**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This PR introduces the usePrint hook for esm apps to reuse when printing
cc @denniskigen @vasharma05 @hadijahkyampeire @pirupius 

## Related Issue

https://openmrs.atlassian.net/browse/O3-3461

### CODE REVIEW

**Comment by jnsereko** [comment]
cc @denniskigen @ibacher

**Comment by brandones** [comment]
This looks like a very thin wrapper for react-to-print. I suggest just to continue using react-to-print. I'll let someone else weigh in, but I would recommend this be closed.

**Comment by jnsereko** [comment]
cc @pirupius

**Comment by jnsereko** [comment]
> This looks like a very thin wrapper for react-to-print. I suggest just to continue using react-to-print. I'll let someone else weigh in, but I would recommend this be closed.

cc @pirupius

**Pull request closed without merging**
