### PR TITLE
O3-1672 - Size and style of left nav items is wrong

### PR DESCRIPTION
**Pull request by Aryangp**
## Requirements
- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

#### For changes to apps
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
The left nav bar have unnecessary indentation which is what I tried to fix please check

## Screenshots
Screenshot_20230106_230552

## Related Issue

https://issues.openmrs.org/browse/O3-1672

### CODE REVIEW

**Comment by denniskigen** [comment]
Hey @Aryangp, thanks for the work! It appears that the changes required for this to match the [design](https://zpl.io/aMwo0oo) accurately extend beyond this one tweak. More specifically, we need to:

- Constrain the height of nav items to 2rem (32px).
- Set the nav item typography to `heading-compact-01` and color `$text-02`.
- Get rid of a bunch of unnecessary style overrides (in https://github.com/openmrs/openmrs-esm-patient-chart/blob/main/packages/esm-patient-common-lib/src/dashboards/dashboardextension.scss and https://github.com/openmrs/openmrs-esm-core/blob/02a06eb182018cfd3f6496b10af615501d3005f7/packages/apps/esm-offline-tools-app/src/dashboard-link.scss).

**Comment by Aryangp** [comment]
thanks @denniskigen  i will do the changes you told me to do and thanks for you inputs it really help

**Comment by jnsereko** [comment]
hey @Aryangp 
are you still working on this??

**Comment by Aryangp** [comment]
yes  @jnsereko I am still working on this issue sorry for delay . I am new to openmrs so . its a little difficult for to understand the code base but i am trying to solve this issue as sone as possible

**Comment by gracepotma** [comment]
Thanks Dennis for your review here :) 
@Aryangp if you are still struggling please be sure to leverage the daily Coffee Chat calls:
What: O3 Troubleshooting for Frontend Developers
When: Monday-thru-Thursday, 11:30am UTC, 2:30pm EAT, 5:00pm IST
Where: https://om.rs/o3coffee

**Comment by denniskigen** [comment]
@jnsereko you'd expressed interest in taking this on. Did you hear back from @Aryangp? If not, do proceed. If you're still available @Aryangp, feel free to work alongside Joshua to get this work done.

**Comment by Aryangp** [comment]
Yeah  I will work with @jnsereko  and finish this issue as soon as possible @gracepotma @denniskigen

**Comment by denniskigen** [comment]
@gracepotma, we had a chat with @Aryangp about this on the coffee break call yesterday, and the sense we got was that the complexity of this task might be a bit higher than what he's looking to get started with at the moment.

**Comment by denniskigen** [comment]
@vasharma05 Wanna have a go at this?

**Comment by denniskigen** [comment]
Fixed in:

- https://github.com/openmrs/openmrs-esm-core/pull/643
- https://github.com/openmrs/openmrs-esm-core/pull/645
- https://github.com/openmrs/openmrs-esm-core/pull/646
- https://github.com/openmrs/openmrs-esm-core/pull/647

**Pull request closed without merging**
