### PR TITLE
MF-603: Fix Location selector shows the wrong list of locations

### PR DESCRIPTION
**Pull request by donaldkibet**
### Description

1. Add `login locations` tag to fetch the correct locations
2. [ticket description](https://issues.openmrs.org/projects/MF/issues/MF-603?filter=allissues)

### CODE REVIEW

**Review by jonathandick — APPROVED** [review]
LGTM

**Review by jonathandick — COMMENTED** [review]
Sorry, one change, can we make this a configuration because not all implementations may use tags. Maybe a boolean which defaults to true called "useLoginLocationTag"

**Comment by brandones** [comment]
@jonathandick Wait, what's the real-world alternative? Are there implementations for which all locations are login locations (including Unknown Location?)? Or is it that a different tag might be used?

**Comment by jonathandick** [comment]
> @jonathandick Wait, what's the real-world alternative? Are there implementations for which all locations are login locations (including Unknown Location?)? Or is it that a different tag might be used?

Currently at ampath, we don't use tags at all. We haven't set up a location hierarchy for our sites. Perhaps we should but I would like to avoid having to set that up in order to get started with O3.0.

**Comment by mseaton** [comment]
@brandones / @jonathandick - just happened to see this, but definitely agree that choosing to have a specific login location attached to the session should be optional, our login screen should not present this question if the server is not configured to support it, and none of the rest of the application is dependent upon the existence of a login location having been selected.

**Comment by jonathandick** [comment]
> @brandones / @jonathandick - just happened to see this, but definitely agree that choosing to have a specific login location attached to the session should be optional, our login screen should not present this question if the server is not configured to support it, and none of the rest of the application is dependent upon the existence of a login location having been selected.

I think this is more about deciding what list of locations to show on login, rather than associating a session with a location.

**Review by FlorianRappl — APPROVED** [review]
LGTM - just run prettier and we are fine. :beers:

**Pull request merged**
