### PR TITLE
(refactor) Replace usages of `/ws/rest/v1/` with `restBaseUrl`

### PR DESCRIPTION
**Pull request by jwnasambu**
# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

Change all instances of the hard-coded API base URL '/ws/rest/v1/' to use the `restBaseUrl` variable instead. This enhances maintainability and flexibility of the API base URL configuration.

## Screenshots
None!

## Related Issue
https://openmrs.atlassian.net/browse/O3-2815

### CODE REVIEW

**Comment by denniskigen** [comment]
@ibacher should we remove the ending slash in [restBaseUrl](https://github.com/openmrs/openmrs-esm-core/blob/3787fda5e6fcf9d75c7fa80aebe48520ac592d36/packages/framework/esm-api/src/openmrs-fetch.ts#L9-L10) so it reads the same as `fhirBaseUrl` and is easier to think about when refactoring?

**Comment by brandones** [comment]
@denniskigen Sounds reasonable to me.

**Comment by denniskigen** [comment]
@jwnasambu now that #935 got merged, please review your work to ensure that there's a trailing slash after each usage of `restBaseUrl`.

**Comment by denniskigen** [comment]
@jwnasambu You'll need to be bump the framework version to get the `restBaseUrl` [mock](https://github.com/openmrs/openmrs-esm-core/pull/940) provided in your testing environment.

**Review by njiddasalifu — COMMENTED** [review]
see some linting failing. consider testing locally if everything is okay.

**Review by denniskigen — APPROVED** [review]
Thanks, @jwnasambu!

**Pull request merged**
