### PR TITLE
(chore) O3-2307 - Update the webpack watch ignore paths

### PR DESCRIPTION
**Pull request by anjula-sack**
## Requirements
- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.

#### For changes to apps
- [x]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

Currenlty there's an issue with the webpack watch mode where it watch for test output files causing the tests to fail. I updated the webpack ignore paths with the correct wildcards.

## Screenshots

None

## Related Issue

https://issues.openmrs.org/browse/O3-2307

## Other

None

### CODE REVIEW

**Comment by denniskigen** [comment]
Does this solve the issue for you when you test locally, @anjula-sack?

**Comment by ibacher** [comment]
@anjula-sack The easiest way to test this is to run the tests in watch mode and (assuming you're using Linux) use `touch` to update a file that should be watched, and confirm you see the tests re-run then use `touch` on, e.g., `test-results/tmpfile` (touch will create the file) and confirm that they aren't re-triggered.

**Comment by anjula-sack** [comment]
> @anjula-sack The easiest way to test this is to run the tests in watch mode and (assuming you're using Linux) use `touch` to update a file that should be watched, and confirm you see the tests re-run then use `touch` on, e.g., `test-results/tmpfile` (touch will create the file) and confirm that they aren't re-triggered.

@ibacher I tried it.  Webpack is not listening for file creations. But what rerender triggers is updating the test-restults/index.html file. This report is being updated while running the tests causing the refresh. I tried with the wild card as well it still the same. BTW i'm updating the webpack config in node modules at the cohort builder not sure whether this is the correct approach.

**Comment by anjula-sack** [comment]
I updated the test files path to ` { outputFolder: "../test-results/report" }` so it will create them outside the project directory and the tests are passing. Since webpack is not watching that file. @ibacher @denniskigen  I tried ignore patterns none of them worked out.

**Comment by denniskigen** [comment]
Yes, @anjula-sack. So do we still need this to get merged in?

**Pull request closed without merging**
